import random


jokes = [
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call fake spaghetti? An impasta!",
    "Why couldn’t the bicycle stand up by itself? It was two-tired!",
    "Why do cows have hooves instead of feet? Because they lactose!",
    "What do you get when you cross a snowman and a vampire? Frostbite!",
    "Why don’t eggs tell jokes? Because they might crack up!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "Why can’t you give Elsa a balloon? Because she will let it go!",
    "Why did the math book look sad? Because it had too many problems.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why did the coffee file a police report? It got mugged!",
    "How does a penguin build its house? Igloos it together!",
    "Why was the belt arrested? For holding up a pair of pants!",
    "What kind of shoes do ninjas wear? Sneakers!",
    "Why do fish live in saltwater? Because pepper makes them sneeze!",
    "Why did the stadium get hot after the game? Because all the fans left!",
    "Why don’t oysters donate to charity? Because they are shellfish!",
    "What did one plate say to the other plate? Dinner’s on me!",
    "Why don’t secret agents tell jokes? Because they keep them classified!",
    "Why did the computer catch a cold? It left its Windows open!",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why do bees have sticky hair? Because they use honeycombs!",
    "Why did the barber win the race? He knew all the short cuts!",
    "What did the big flower say to the little flower? Hey, bud!",
    "Why did the cookie go to the hospital? Because it felt crummy!",
    "Why don’t trees use social media? Because they don’t want to be logged in!",
    "Why did the banana go to the doctor? Because it wasn’t peeling well!",
    "What did the fish say when it hit the wall? Dam!",
    "Why don’t cannibals eat clowns? Because they taste funny!",
    "Why did the astronaut break up with his girlfriend? Because he needed space!",
    "Why don’t mountains get tired? Because they peak all the time!",
    "Why did the football coach go to the bank? To get his quarterback!",
    "What did the left eye say to the right eye? Between us, something smells!",
    "What do you call a sleeping bull? A bulldozer!",
    "Why do vampires always seem sick? Because they’re always coffin!",
    "What kind of music do balloons hate? Pop!",
    "Why was the math teacher suspicious? He was acting too shady!",
    "What did one wall say to the other wall? Meet you at the corner!",
    "Why did the grape stop in the middle of the road? Because it ran out of juice!",
    "Why do skeletons make bad liars? Because you can see right through them!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why did the belt go to jail? Because it was holding up pants!",
    "What kind of bagel can fly? A plain bagel!",
    "What did the zero say to the eight? Nice belt!",
    "Why did the orange stop rolling? Because it ran out of juice!",
    "What’s a skeleton’s least favorite room? The living room!",
    "Why was the music teacher’s ladder broken? Because it had too many steps!",
    "Why don’t farmers tell jokes? Because their cows might have a beef with it!"
]

print(random.choices(jokes))